### PR TITLE
[DS-280] Fix multiple schema initialization

### PR DESCRIPTION
**Pull request by starsprung**
### Description
Prevent schema being initialized for every request, which causes significant performance degradation with large numbers of routes. Protection against multiple initialization was removed in https://github.com/auth0/ratify/pull/7/files#diff-75b96d5769e228e23cf086daa89fcd4b7b5e290938b5c3e78c58dfb4b5e5d9aeL218.

### References
https://auth0team.atlassian.net/browse/DS-280

### CODE REVIEW

**Review by ArturKlajnerok — APPROVED** [review]

**Review by ArturKlajnerok — COMMENTED** [review]
Fox context: 
Screen Shot 2022-08-17 at 15 10 12

**Review by ArturKlajnerok — COMMENTED** [review]
CPU & Event loop lag drop on layer0 space with this fix: 
Screenshot 2022-08-18 at 12 04 50

**Review by ArturKlajnerok — COMMENTED** [review]
CPU & Event loop lag drop on sus1 with this fix:
Screenshot 2022-08-18 at 15 30 56
Screenshot 2022-08-18 at 15 33 01

**Review by ArturKlajnerok — COMMENTED** [review]
Should we bump the lib version?

**Comment by DJMcK** [comment]
Nice work team! 

Just one thought if we wanted to go slightly further. Might be worth considering if `onPreStart` will work for us; giving us a _one-time_ event after all the registrations complete but before any listeners start.

Save it triggering on every request.

```ts
server.ext('onPreStart', (server) => {});
```

The big efficiency gain is definitely in what we've done already so 👍  this would be minor.

**Pull request merged**
